url: https://brittleigh.github.io
baseurl: /alex-maschoff/




# Site settings
title: Alex Maschoff
email: alex.maschoff@gmail.com
description: "One awesome, driven dude."

# Team names, titles and social links
people:
- name: Alex Maschoff
  pic: alex-maschoff.jpg
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/alexmaschoff
    - title: facebook
      url: https://www.facebook.com/alex.maschoff.3
    - title: linkedin
      url: https://www.linkedin.com/in/alex-maschoff-3a861a31/

- #name: Larry Parker
  #pic: 2
  #position: Lead Marketer
  #social:
    - #title: twitter
      #url: #
    - #title: facebook
      #url: #
    - #title: linkedin
      #url: #

- #name: Diana Petersen
  #pic: 3
  #position: Lead Developer
  #social:
    - #title: twitter
      #url: #
    - #title: facebook
      #url: #
    - #title: google-plus
      #url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty